// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZyO5umKV4IwAlFexqLBOqkJz_W_MHt9M',
    appId: '1:335005047323:web:474db2c08784b789c176be',
    messagingSenderId: '335005047323',
    projectId: 'v-comm-25582',
    authDomain: 'v-comm-25582.firebaseapp.com',
    databaseURL: 'https://v-comm-25582-default-rtdb.firebaseio.com',
    storageBucket: 'v-comm-25582.firebasestorage.app',
    measurementId: 'G-DHT36PTRQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4RCRI-QaLGH11tt1m5UC_NcwEtjfu_pA',
    appId: '1:335005047323:android:8fec23c827fd9046c176be',
    messagingSenderId: '335005047323',
    projectId: 'v-comm-25582',
    databaseURL: 'https://v-comm-25582-default-rtdb.firebaseio.com',
    storageBucket: 'v-comm-25582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSsWASV3Iz2ySfvk734f5P3tPp2LFhTs4',
    appId: '1:335005047323:ios:eaa57c5fa654f6adc176be',
    messagingSenderId: '335005047323',
    projectId: 'v-comm-25582',
    databaseURL: 'https://v-comm-25582-default-rtdb.firebaseio.com',
    storageBucket: 'v-comm-25582.firebasestorage.app',
    iosBundleId: 'com.example.vComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSsWASV3Iz2ySfvk734f5P3tPp2LFhTs4',
    appId: '1:335005047323:ios:eaa57c5fa654f6adc176be',
    messagingSenderId: '335005047323',
    projectId: 'v-comm-25582',
    databaseURL: 'https://v-comm-25582-default-rtdb.firebaseio.com',
    storageBucket: 'v-comm-25582.firebasestorage.app',
    iosBundleId: 'com.example.vComm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZyO5umKV4IwAlFexqLBOqkJz_W_MHt9M',
    appId: '1:335005047323:web:8318c2836ca46a4cc176be',
    messagingSenderId: '335005047323',
    projectId: 'v-comm-25582',
    authDomain: 'v-comm-25582.firebaseapp.com',
    databaseURL: 'https://v-comm-25582-default-rtdb.firebaseio.com',
    storageBucket: 'v-comm-25582.firebasestorage.app',
    measurementId: 'G-BW4GJY6R4D',
  );

}